### ISSUE TITLE
CMakeLists.txt in python install dir could not find msis2driver.f90

### ISSUE THREAD

**Issue by petermao** [space-physics/nrlmsis2.0#1]
* operating system (MacOS (Darwin 19.6.0)
* compiler & version (gcc 9.4.0)
* Python version (3.7.12)

after your standard build process, I ran `python setup.py install --user` from the top dir.  During the first run of msis2.run(), it tries to compile (again) and the CMakeLists.txt in the python install (`~/Library/Python/3.7/lib/python/site-packages/msis2-0.9.0-py3.7.egg/msis2/CMakeLists.txt` for me) needed the full path to msis2driver.f90.

**Comment by ROINT** [comment]
I wanna ask whether you solve this problem?

**Comment by scivision** [comment]
Hi Sorry, this package is obsolete and not maintained anymore
